services:
  - type: web
    name: istanbul-sultan-palace-ruby-track
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    autoDeploy: true
